# UI Component sizes

ROWS = 150
COLS = 200
CELL_WIDTH = 5
CELL_HEIGHT = CELL_WIDTH
BUTTON_STRIP_HEIGHT = 50
BUTTON_STRIP_TOP = ROWS * CELL_HEIGHT
WINDOW_WIDTH = COLS * CELL_WIDTH
WINDOW_HEIGHT = BUTTON_STRIP_TOP + BUTTON_STRIP_HEIGHT

# Button labels

CLEAR_BUTTON_LABEL = "CLEAR"
CREATE_MAZE_BUTTON_LABEL = "CREATE MAZE"
SOLVE_MAZE_BUTTON_LABEL = "SOLVE MAZE"
QUIT_BUTTON_LABEL = "QUIT"

# RGB Colors

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
GREY = (125, 125, 125)


